# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll.xci
# IP: The module: 'adc_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/adc_ethernet/ad9226_ethernet/adc_ethernet.srcs/sources_1/ip/adc_pll/adc_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
