# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7102/demo/18_an108_adda_vga_test/an108_adda_vga_test/an108_adda_vga_test.srcs/sources_1/ip/da_rom/da_rom.xci
# IP: The module: 'da_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/18_an108_adda_vga_test/an108_adda_vga_test/an108_adda_vga_test.srcs/sources_1/ip/da_rom/da_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'da_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7102/demo/18_an108_adda_vga_test/an108_adda_vga_test/an108_adda_vga_test.srcs/sources_1/ip/da_rom/da_rom.xci
# IP: The module: 'da_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/18_an108_adda_vga_test/an108_adda_vga_test/an108_adda_vga_test.srcs/sources_1/ip/da_rom/da_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'da_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
