# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  create_project -in_memory -part xc7a100tfgg484-2
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/demo_ax7101/demo/12_ibert_demo/ibert_demo/ibert_7series_gtp_0_example/ibert_7series_gtp_0_example.cache/wt [current_project]
  set_property parent.project_path D:/demo_ax7101/demo/12_ibert_demo/ibert_demo/ibert_7series_gtp_0_example/ibert_7series_gtp_0_example.xpr [current_project]
  set_property ip_cache_permissions disable [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  add_files -quiet D:/demo_ax7101/demo/12_ibert_demo/ibert_demo/ibert_7series_gtp_0_example/ibert_7series_gtp_0_example.runs/synth_1/example_ibert_7series_gtp_0.dcp
  read_ip -quiet D:/demo_ax7101/demo/12_ibert_demo/ibert_demo/ibert_7series_gtp_0_example/ibert_7series_gtp_0_example.srcs/sources_1/ip/ibert_7series_gtp_0/ibert_7series_gtp_0.xci
  read_xdc D:/demo_ax7101/demo/12_ibert_demo/ibert_demo/ibert_7series_gtp_0_example/ibert_7series_gtp_0_example.srcs/constrs_1/imports/example_design/example_ibert_7series_gtp_0.xdc
  link_design -top example_ibert_7series_gtp_0 -part xc7a100tfgg484-2
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force example_ibert_7series_gtp_0_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file example_ibert_7series_gtp_0_drc_opted.rpt -pb example_ibert_7series_gtp_0_drc_opted.pb -rpx example_ibert_7series_gtp_0_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  implement_debug_core 
  place_design -directive ExtraNetDelay_high
  write_checkpoint -force example_ibert_7series_gtp_0_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file example_ibert_7series_gtp_0_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file example_ibert_7series_gtp_0_utilization_placed.rpt -pb example_ibert_7series_gtp_0_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file example_ibert_7series_gtp_0_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design -directive Explore
  write_checkpoint -force example_ibert_7series_gtp_0_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force example_ibert_7series_gtp_0_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file example_ibert_7series_gtp_0_drc_routed.rpt -pb example_ibert_7series_gtp_0_drc_routed.pb -rpx example_ibert_7series_gtp_0_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file example_ibert_7series_gtp_0_methodology_drc_routed.rpt -pb example_ibert_7series_gtp_0_methodology_drc_routed.pb -rpx example_ibert_7series_gtp_0_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file example_ibert_7series_gtp_0_power_routed.rpt -pb example_ibert_7series_gtp_0_power_summary_routed.pb -rpx example_ibert_7series_gtp_0_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file example_ibert_7series_gtp_0_route_status.rpt -pb example_ibert_7series_gtp_0_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file example_ibert_7series_gtp_0_timing_summary_routed.rpt -rpx example_ibert_7series_gtp_0_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file example_ibert_7series_gtp_0_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file example_ibert_7series_gtp_0_clock_utilization_routed.rpt"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force example_ibert_7series_gtp_0_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
  catch { write_mem_info -force example_ibert_7series_gtp_0.mmi }
  write_bitstream -force example_ibert_7series_gtp_0.bit 
  catch {write_debug_probes -quiet -force example_ibert_7series_gtp_0}
  catch {file copy -force example_ibert_7series_gtp_0.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

