# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7102/demo/16_ad9226_vga_test/ad9226_vga_test/ad9226_vga_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8.xci
# IP: The module: 'dpram1024x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/16_ad9226_vga_test/ad9226_vga_test/ad9226_vga_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram1024x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7102/demo/16_ad9226_vga_test/ad9226_vga_test/ad9226_vga_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8.xci
# IP: The module: 'dpram1024x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/16_ad9226_vga_test/ad9226_vga_test/ad9226_vga_test.srcs/sources_1/ip/dpram1024x8/dpram1024x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram1024x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
