# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o.xci
# IP: The module: 'fifo_2048_32i_8o' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o.xci
# IP: The module: 'fifo_2048_32i_8o' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/gtp_video/15_ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel/ddr3_an5642_vga_sobel.srcs/sources_1/ip/fifo_2048_32i_8o/fifo_2048_32i_8o_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_2048_32i_8o'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
