# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256.xci
# IP: The module: 'afifo_64_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256/afifo_64_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256/afifo_64_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256.xci
# IP: The module: 'afifo_64_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256/afifo_64_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256/afifo_64_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/10_audio_record_play/audio_record_play/audio_record_play.srcs/sources_1/ip/afifo_64_256/afifo_64_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
