# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/video_ethernet.xdc

# IP: new/ip/sys_pll/sys_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_pll || ORIG_REF_NAME==sys_pll} -quiet] -quiet
