# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll.xci
# IP: The module: 'video_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll.xci
# IP: The module: 'video_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/08_1_vga_test/vga_test/vga_test.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
