# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7101/demo/09_ddr3_test/ddr3_test/ddr3_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
