# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
# IP: The module: 'afifo_16i_64o_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512.xci
# IP: The module: 'afifo_16i_64o_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7102/demo/adc_ethnet/ddr3_an5642_an430_lcd/ddr3_an5642_an430_lcd.srcs/sources_1/ip/afifo_16i_64o_512/afifo_16i_64o_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_16i_64o_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
