# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddr3_ov5640_vga.xdc

# IP: ip/gtp/gtp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtp || ORIG_REF_NAME==gtp} -quiet] -quiet

# IP: ip/fifo_4096_16i_32o/fifo_4096_16i_32o.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_4096_16i_32o || ORIG_REF_NAME==fifo_4096_16i_32o} -quiet] -quiet
