# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.cache/wt [current_project]
set_property parent.project_path D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/arp_cache.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/rx/arp_rx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/arp_tx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/debouce/ax_debounce.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/imports/rtl/crc.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/imports/src/ethernet_test.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/icmp_reply.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/rx/ip_rx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/ip_tx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/ip_tx_mode.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/rx/mac_rx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/rx/mac_rx_top.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/mac_test.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/mac_top.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx_mode.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx_top.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/rx/udp_rx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/mac/tx/udp_tx.v
  D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/new/ethernet_4port.v
}
read_ip -quiet D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc]

read_ip -quiet D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc]

read_ip -quiet D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc]

read_ip -quiet D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/demo_ax7101/TCP_UDP_ARP_ax7050/rgmii_ethernet/eth_test.srcs/constrs_1/new/top.xdc]


synth_design -top ethernet_4port -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ethernet_4port.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ethernet_4port_utilization_synth.rpt -pb ethernet_4port_utilization_synth.pb"
